name: Synchronize Thcrap Chinese branch patch file.
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0/6 * * *'
jobs:
  Download_latest_patch_file_and_save:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull the latest patch file from the main source server (https://srv.thpatch.net/lang_zh-hans/)
      run: |
        cd ./TimingSync
        sudo wget -tries=10 https://srv.thpatch.net/lang_zh-hans/files.js
        sudo chmod +x ./PatchFileSync
        ./PatchFileSync repo_files.js files.js
        sudo rm -f repo_files.js
        sudo cp files.js ../lang_zh-hans/files.js
        sudo mv files.js repo_files.js
            
    - name: Pull the latest hook config files from thcrap-tsa（https://github.com/thpatch/thcrap-tsa）
      run: |
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/aero
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tasofro
        svn checkout https://github.com/thpatch/thcrap-tsa/trunk/base_tsa
            
    - name: Push the patch file to the GitHub repository.
      env:
          GITHUB_TOKEN: ${{ secrets.SYNCHONIZE_TOKEN }}
      run: |
        git config user.name "ROCO2021"
        git config user.email "1401548627@qq.com" 
        git add .
        git status
        git commit -m $(echo -e "定时补丁文件更新。`date "+%Y-%m-%d===>%H:%M"`(UTC)")
        git push https://$GITHUB_TOKEN@github.com/ROCO-freedom/Thpatch_CN_Mirror.git
      
    - name: If failed to push GitHub repository.
      if: failure()
      run:
        echo "No need to update patch file in GitHub."
    
    - name: Push the latest file to Coding repository.
      if: always()
      env:
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
          CODING_NAME: ${{ secrets.CODING_NAME }}
      run: |
        sudo cp ./TimingSync/.gitignore ./.gitignore
        sudo rm -rf ./.github ./aero/.svn/ ./base_tasofro/.svn/ ./base_tsa/.svn/ ./TimingSync
        git config user.name "ROCO2021"
        git config user.email "1401548627@qq.com" 
        git add .
        git status
        git commit -m $(echo -e "同步至国内仓库。`date "+%Y-%m-%d===>%H:%M"`(UTC)")
        git push https://${CODING_NAME}:${CODING_TOKEN}@e.coding.net/thpatch-cn/thcrapcn/Thpatch_CN_Patchfiles_Mirror.git
        
    - name: If failed to push GitHub repository.
      if: failure()
      run:
        echo "No need to synchonize the patch file."
